version: '3.9'

services:
  app:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/items
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/items --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MONGO_INITDB_DATABASE=items
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
